"""Request Model

Revision ID: af25b2a7c8eb
Revises: 83842a38ad1d
Create Date: 2025-09-24 22:24:27.643495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af25b2a7c8eb'
down_revision: Union[str, Sequence[str], None] = '83842a38ad1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    userrole_enum = sa.Enum('USER', 'PROVIDER_INDIVIDUAL', 'PROVIDER_ORGANIZATION', name='userrole')
    userrole_enum.create(op.get_bind())
    
    # Add columns with default value for role
    op.add_column('users', sa.Column('role', userrole_enum, nullable=False, server_default='USER'))
    op.add_column('users', sa.Column('service_type', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('experience', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('contact_info', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('team_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'team_size')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'contact_info')
    op.drop_column('users', 'experience')
    op.drop_column('users', 'service_type')
    op.drop_column('users', 'role')
    
    # Drop the enum type
    userrole_enum = sa.Enum('USER', 'PROVIDER_INDIVIDUAL', 'PROVIDER_ORGANIZATION', name='userrole')
    userrole_enum.drop(op.get_bind())
    # ### end Alembic commands ###
