"""Request Model

Revision ID: bb8876066dc9
Revises: af25b2a7c8eb
Create Date: 2025-09-24 22:58:47.346052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID

# revision identifiers, used by Alembic.
revision: str = 'bb8876066dc9'
down_revision: Union[str, Sequence[str], None] = 'af25b2a7c8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact_info', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('provider_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('repair_requests', sa.Column('voice_file', sa.String(length=500), nullable=True))
    op.alter_column('repair_requests', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repair_requests', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('repair_requests', 'voice_file')
    op.drop_table('services')
    # ### end Alembic commands ###
